2019-05-20 10:13:55.385 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 10:13:55.556 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 10:14:02.549 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 6d0a60d0-78ec-4b54-97a5-abc5e569e474
2019-05-20 11:10:20.658 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 11:10:20.955 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 11:10:28.388 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 61080cce-63c1-4d73-acbb-3b3d0e35bfcc
2019-05-20 11:28:09.503 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 11:28:09.758 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 11:28:41.651 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 23872873-7dc1-4f86-9655-e4c97c86c635
2019-05-20 11:31:55.748 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 11:31:55.998 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 11:32:17.466 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = d2315bd6-163c-4942-bc56-a06ce54a7a17
2019-05-20 11:37:24.363 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 11:37:24.582 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 11:37:31.146 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 07519d21-56ec-40b6-a5b7-47065ad1dae8
2019-05-20 12:01:29.362 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 12:01:29.783 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 12:01:38.556 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:47.913 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 12:01:48.152 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 12:01:48.407 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:48.426 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateIncomingMessageBehavior.<InvokeIncomingMessageMutators>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.UnitOfWorkBehavior.<InvokeUnitsOfWork>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.UnitOfWorkBehavior.<InvokeUnitsOfWork>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateIncomingTransportMessageBehavior.<InvokeIncomingTransportMessagesMutators>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:48.462 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:48.469 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:48.492 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:48.492 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:48.523 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:48.523 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:48.554 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:48.554 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:48.586 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:48.586 WARN  NServiceBus.RecoverabilityExecutor Delayed Retry will reschedule message '7ec7ca31-5faa-481d-afd6-aa530094c411' after a delay of 00:00:10 because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:57.415 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:01:57.415 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:57.447 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:01:57.447 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:57.478 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:01:57.478 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:57.509 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:01:57.509 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:57.540 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:01:57.540 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:57.572 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:01:57.572 WARN  NServiceBus.RecoverabilityExecutor Delayed Retry will reschedule message '39283bea-b7ee-4359-943b-aa530094da42' after a delay of 00:00:10 because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:59.431 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:59.431 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:59.462 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:59.462 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:59.493 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:59.493 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:59.525 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:59.525 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:59.556 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:59.556 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '7ec7ca31-5faa-481d-afd6-aa530094c411' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:01:59.587 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 12:01:59.587 WARN  NServiceBus.RecoverabilityExecutor Delayed Retry will reschedule message '7ec7ca31-5faa-481d-afd6-aa530094c411' after a delay of 00:00:20 because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:02:08.506 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:02:08.506 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:02:08.537 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:02:08.537 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:02:08.568 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:02:08.568 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:02:08.600 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:02:08.600 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:02:08.631 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:02:08.631 INFO  NServiceBus.RecoverabilityExecutor Immediate Retry is going to retry message '39283bea-b7ee-4359-943b-aa530094da42' because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 12:02:08.663 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 12:02:08.663 WARN  NServiceBus.RecoverabilityExecutor Delayed Retry will reschedule message '39283bea-b7ee-4359-943b-aa530094da42' after a delay of 00:00:20 because of an exception:
System.Exception: BOOM
   at Sales.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\PlaceOrderHadler.cs:line 18
   at lambda_method(Closure , Object , Object , IMessageHandlerContext )
   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext)
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at (Closure`2 , IInvokeHandlerContext )
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext()
2019-05-20 14:32:56.295 INFO  DefaultFactory Logging to 'C:\Users\karyn\OneDrive\Рабочий стол\RetailDemo\Sales\bin\Debug\' with level Info
2019-05-20 14:32:56.507 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2019-05-17'.

2019-05-20 14:32:57.825 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 935fd7d5-6e41-4bda-ae20-fc0f385f5707
2019-05-20 14:32:57.886 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = e4c83cf2-377d-495d-aad1-78b82e7031c3
2019-05-20 14:33:04.180 INFO  Sales.PlaceOrderHandler Received PlaceOrder, OrderId = 726792f9-3454-4a2e-998b-c7a197be6aa5
